version: 2.1

jobs:
  build:
    parameters:
      python_image:
        type: string

      postgres_image:
        type: string

    environment:
      DEBUG: 'True'

    docker:
      - image: <<parameters.python_image>>

      - image: <<parameters.postgres_image>>
        environment:
          POSTGRES_USER: postgres
          POSTGRES_DB: postgres
          POSTGRES_PASSWORD: password

    steps:
      - checkout
      - run:
          name: Wait for db to become available
          command: dockerize -wait tcp://localhost:5432 -timeout 1m

      - restore_cache:
          keys:
            - v1-<<parameters.python_image>>-{{ checksum "requirements.txt" }}
          paths:
            - ./venv

      - run:
          name: Install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt

      - save_cache:
          name: Save pip cache
          key: v1-<<parameters.python_image>>-{{ checksum "requirements.txt" }}
          paths:
            - ./venv

      - run:
          name: Run tests
          command: |
            . venv/bin/activate
            python -m pytest -s -vvv app/enquiries/tests

workflows:
  version: 2

  Default build:
    jobs:
      - build:
          python_image: circleci/python:3.6.4
          postgres_image: circleci/postgres:9.6